manifest:
  remotes:
    - name: sekigon-gonnoc
      url-base: https://github.com/sekigon-gonnoc
  projects:
    - name: zmk-feature-non-lipo-battery-management
      remote: sekigon-gonnoc
      revision: main